site_name: AI Quickstart
site_url: https://aiquickst.art
theme:
  name: material

nav:
  - Home: index.md

  - AI with Python:
    - Overview: python/index.md
    - Onboarding: python/onboarding.md
    - GitHub Codespaces: python/github_codespaces.md
    - GitHub Models: python/github_models.md

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/getaiquickstart


